### ISSUE TITLE
ALAssetsLibrary In WAStickers is deprecated

### ISSUE THREAD

**Issue by Murdo-C** [Fluffcorn/ios-sticker-packs-app#6]
The ALAssetsLibrary has been replaced by the new Photos framework - the app doesn’t compile in the latest Xcode as a result.

**Comment by ansonl** [comment]
I will refactor the code in the next Fluffcorn Stickers app update.

**Comment by ansonl** [comment]
@CaptainMurdo ALAssetsLibrary is being used by YYImageCode which is part of the WhatsApp stickers (WAStickers) code which was imported from https://github.com/WhatsApp/stickers/blob/main/iOS/WAStickersThirdParty/YYImageCoder.m
The latest version of WAStickers code from WhatsApp still uses ALAssetsLibrary and updates to the WAStickers code will be imported from the official WhatsApp stickers repository when fixed by WhatsApp. 

I can still successfully compile the current project in Xcode even though it warns about the deprecated code. If you don't need WhatsApp integration, you could remove the WhatsApp code files and compile without them.
